filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log"]
    input:
      ignore_older: 0
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log"]
    input:
      ignore_older: 0

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

logging.level: info
